use "atlas-scripts-sml/Lattice.sml";
use "atlas-scripts-sml/LatticeAT.sml";
use "atlas-scripts-sml/RootDatum.sml";
use "atlas-scripts-sml/poset.sml";
use "atlas-scripts-sml/MatrixAT.sml";
use "atlas-scripts-sml/WeylElt.sml";
use "atlas-scripts-sml/elliptic.sml";

(*
  File: atlas-scripts-sml/W_order.sml

  Purpose
  - Partial SML translation of `atlas-scripts/W_order.at`.
  - The `.at` file explores a partial order on (elliptic) Weyl-group conjugacy
    classes derived from a dominance order on certain “good” dominant
    coweights/invariants attached to each class.

  Status / scope
  - This port currently provides the *generic dominance-order machinery*:
      - `less(rd,v,w)` — dominance comparison test (in terms of the cone
        generated by simple coroots).
      - `vec_poset(S,rd)` — build an adjacency-list poset from a list of
        vectors `S` using `less`.
  - The remaining `.at` functionality depends on `good_W_representatives.at`
    (not yet ported) via `good_info`, which attaches a canonical dominant
    vector `v` to each Weyl element representing a conjugacy class.  Without
    that, we cannot reconstruct the intended `W_poset`, `W_graph`, or
    `elliptic_W_Graph` from *just* a list of Weyl elements.

  Design notes (how the dominance test is implemented)
  - In the `.at` script:
      less(rd,v,w) =
        is_positive (requisition (solve (simple_coroots(rd), v-w))).
  - Here we interpret this as:
      (w - v) is a nonnegative Z-linear combination of simple coroots.
    We compute one rational solution to A*x = (v - w), where A is the matrix
    whose columns are the simple coroots, and then check all coordinates x_i
    are >= 0.

  Limitations
  - This test assumes `v` and `w` are expressed in a coordinate system
    compatible with `RootDatum.simpleCorootsMat`.
  - If the system is under-/over-determined (e.g. torus factors), the solver
    may fail; in that case we conservatively return `false`.
*)

structure W_order = struct
  type rootdatum = RootDatum.t
  type ratvec = Lattice.ratvec
  type weyl = WeylElt.t

  fun bigrat_ge0 (q: LatticeAT.BigRat.t) : bool =
    let
      val q' = LatticeAT.BigRat.normalize q
    in
      #num q' >= (0 : IntInf.int)
    end

  (* Dominance order on (assumed-dominant) coweights/vectors:
     `less(rd,v,w)` holds when `v <= w` in dominance order. *)
  fun less (rd: rootdatum, v: ratvec, w: ratvec) : bool =
    let
      val a = RootDatum.simpleCorootsMat rd
      val diff = Lattice.ratvecSub (v, w)
    in
      case LatticeAT.solve_ratvec (a, diff) of
        NONE => false
      | SOME xs => List.all bigrat_ge0 xs
    end

  (* Extract the vector list in the `.at` development from `good_info`.

     Not yet supported (depends on `good_W_representatives.at`). *)
  fun vecs (_: weyl list) : ratvec list =
    raise Fail "W_order.vecs: not yet ported (requires good_W_representatives/good_info)"

  (* Build a poset adjacency list from vectors `S` using the dominance test. *)
  fun vec_poset (S: ratvec list, rd: rootdatum) : Poset.t =
    let
      val n = length S
      fun row i =
        let
          val vi = List.nth (S, i)
          fun ok j = less (rd, vi, List.nth (S, j))
          val js = List.filter ok (List.tabulate (n, fn k => k))
        in
          js
        end
    in
      List.tabulate (n, row)
    end

  (* As in the `.at` file, but not yet supported without `good_info`. *)
  fun W_poset (_: weyl list) : Poset.t =
    raise Fail "W_order.W_poset: not yet ported (requires good_W_representatives/good_info)"

  (* Convenience: graph a vector-poset with numeric labels. *)
  fun vec_graph (S: ratvec list, rd: rootdatum) : string =
    Poset.graph (vec_poset (S, rd))

  (* As in the `.at` file, but not yet supported without `good_info`. *)
  fun W_graph (_: weyl list) : string =
    raise Fail "W_order.W_graph: not yet ported (requires good_W_representatives/good_info)"

  (* As in the `.at` file, but not yet supported without `good_info`. *)
  fun elliptic_W_Graph (_: rootdatum) : string =
    raise Fail "W_order.elliptic_W_Graph: not yet ported (requires good_W_representatives/good_info)"

  (* Minimal label helper that does not depend on `good_info`. Useful for
     ad-hoc graphs when callers supply their own poset. *)
  fun label_order_length (w: weyl) : string =
    let
      val ord = MatrixAT.order (#mat w)
      val len = WeylElt.length w
    in
      Int.toString ord ^ ":" ^ Int.toString len
    end
end
